[package]
name = "async-forward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
pin-project = "1.0.12"

[dev-dependencies]
cool_asserts = "2.0.3"
rand = "0.8.5"
